{
 "title": "Hive",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Block Number",
   "type": "stat",
   "description": "Current Hive block height",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "block_stat_num{job=\"hived\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Utilization (Current)",
   "type": "gauge",
   "description": "Current block space used",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(block_stat_size{job=\"hived\"} * 100) / 65536",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Utilization (5m)",
   "type": "gauge",
   "description": "Block space used in the last 5 minutes",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg_over_time(block_stat_size{job=\"hived\"}[5m]) * 100) / 65536",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Utilization (1h)",
   "type": "gauge",
   "description": "Block space used in the last 1 hour",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg_over_time(block_stat_size{job=\"hived\"}[1h]) * 100) / 65536",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Block Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Transactions",
   "type": "timeseries",
   "description": "Hive transactions per block",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "block_stat_txs{job=\"hived\"}",
     "legendFormat": "Transactions Count"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "timeseries",
   "description": "Raw binary block size",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "block_stat_size{job=\"hived\"}",
     "legendFormat": "Block Size"
    },
    {
     "expr": "avg_over_time(block_stat_size{job=\"hived\"}[5m])",
     "legendFormat": "Block Size (5 minute MA)"
    }
   ]
  },
  {
   "title": "Block Time Offset",
   "type": "timeseries",
   "description": "Time difference between block slot time and received time",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "block_stat_offset{job=\"hived\"}",
     "legendFormat": "Block Time Offset"
    },
    {
     "expr": "avg_over_time(block_stat_offset{job=\"hived\"}[5m])",
     "legendFormat": "Block Time Offset (5 minute MA)"
    }
   ]
  },
  {
   "title": "Transactions Processed Before Block",
   "type": "timeseries",
   "description": "Transactions processed during pre-validation",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "block_stat_before_txs_processed{job=\"hived\"}",
     "legendFormat": "Processed"
    },
    {
     "expr": "block_stat_before_txs_accepted{job=\"hived\"}",
     "legendFormat": "Accepted"
    },
    {
     "expr": "block_stat_before_txs_failed_auth{job=\"hived\"}",
     "legendFormat": "Auth Failed"
    },
    {
     "expr": "block_stat_before_txs_with_no_rc{job=\"hived\"}",
     "legendFormat": "No RC"
    }
   ]
  },
  {
   "title": "Transactions During Block Post Processing",
   "type": "timeseries",
   "description": "Transaction status after processing block",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "block_stat_after_txs_expired{job=\"hived\"}",
     "legendFormat": "Expired"
    },
    {
     "expr": "block_stat_after_txs_failed{job=\"hived\"}",
     "legendFormat": "Failed"
    },
    {
     "expr": "block_stat_after_txs_reapplied{job=\"hived\"}",
     "legendFormat": "Re-applied"
    },
    {
     "expr": "block_stat_after_txs_postponed{job=\"hived\"}",
     "legendFormat": "Postponed"
    }
   ]
  },
  {
   "title": "Block Execution Times",
   "type": "timeseries",
   "description": "Breakdown of block execution times",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "block_stat_exec_wait_time{job=\"hived\"}",
     "legendFormat": "Waiting Time"
    },
    {
     "expr": "block_stat_exec_cleanup_time{job=\"hived\"}",
     "legendFormat": "Cleanup Time"
    },
    {
     "expr": "block_stat_exec_work_time{job=\"hived\"}",
     "legendFormat": "Working Time"
    }
   ]
  },
  {
   "title": "Block Execution Total Time",
   "type": "timeseries",
   "description": "Total block execution time",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "block_stat_exec_total_time{job=\"hived\"}",
     "legendFormat": "Total Time"
    },
    {
     "expr": "avg_over_time(block_stat_exec_total_time{job=\"hived\"}[5m])",
     "legendFormat": "Total Time (5 minute MA)"
    }
   ]
  }
 ]
}