{
 "title": "Hive",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Block Number",
   "type": "stat",
   "description": "Current Hive block height",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "block_stat_num{job=\"hived\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Utilization (Current)",
   "type": "gauge",
   "description": "Current block space used",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(block_stat_size{job=\"hived\"} * 100) / ignoring(job,instance) dgp_maximum_block_size{job=\"hived_api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Utilization (5m)",
   "type": "gauge",
   "description": "Block space used in the last 5 minutes",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg_over_time(block_stat_size{job=\"hived\"}[5m]) * 100) / ignoring(job,instance) avg_over_time(dgp_maximum_block_size{job=\"hived_api\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Utilization (1h)",
   "type": "gauge",
   "description": "Block space used in the last 1 hour",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg_over_time(block_stat_size{job=\"hived\"}[1h]) * 100) / ignoring(job,instance) avg_over_time(dgp_maximum_block_size{job=\"hived_api\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "market_info_hive{job=\"hived_api\", key=\"price\"}",
     "legendFormat": "Price"
    }
   ]
  },
  {
   "title": "HBD Debt Ratio",
   "type": "gauge",
   "description": "Current HBD debt ratio based on current market price",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*(dgp_current_hbd_supply{job=\"hived_api\"}/1000 - ignoring(name) account_hbd_balance{name=\"hive.fund\"}) / ((dgp_virtual_supply{job=\"hived_api\"}/1000) * ignoring(key,currency) market_info_hive{job=\"hived_api\", key=\"price\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "market_info_hive{job=\"hived_api\", key=\"market_cap\"}",
     "legendFormat": "Market Cap"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dgp_hbd_interest_rate{job=\"hived_api\"} / 100",
     "legendFormat": "HBD APR"
    }
   ]
  },
  { "title": "Block Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Transactions",
   "type": "timeseries",
   "description": "Hive transactions per block",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "block_stat_txs{job=\"hived\"}",
     "legendFormat": "Transactions Count"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "timeseries",
   "description": "Raw binary block size",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "block_stat_size{job=\"hived\"}",
     "legendFormat": "Block Size"
    },
    {
     "expr": "avg_over_time(block_stat_size{job=\"hived\"}[5m])",
     "legendFormat": "Block Size (5 minute MA)"
    }
   ]
  },
  {
   "title": "Block Time Offset",
   "type": "timeseries",
   "description": "Time difference between block slot time and received time",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "block_stat_offset{job=\"hived\"}",
     "legendFormat": "Block Time Offset"
    },
    {
     "expr": "avg_over_time(block_stat_offset{job=\"hived\"}[5m])",
     "legendFormat": "Block Time Offset (5 minute MA)"
    }
   ]
  },
  {
   "title": "Transactions Processed Before Block",
   "type": "timeseries",
   "description": "Transactions processed during pre-validation",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "block_stat_before_txs_processed{job=\"hived\"}",
     "legendFormat": "Processed"
    },
    {
     "expr": "block_stat_before_txs_accepted{job=\"hived\"}",
     "legendFormat": "Accepted"
    },
    {
     "expr": "block_stat_before_txs_failed_auth{job=\"hived\"}",
     "legendFormat": "Auth Failed"
    },
    {
     "expr": "block_stat_before_txs_with_no_rc{job=\"hived\"}",
     "legendFormat": "No RC"
    }
   ]
  },
  {
   "title": "Transactions During Block Post Processing",
   "type": "timeseries",
   "description": "Transaction status after processing block",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "block_stat_after_txs_expired{job=\"hived\"}",
     "legendFormat": "Expired"
    },
    {
     "expr": "block_stat_after_txs_failed{job=\"hived\"}",
     "legendFormat": "Failed"
    },
    {
     "expr": "block_stat_after_txs_reapplied{job=\"hived\"}",
     "legendFormat": "Re-applied"
    },
    {
     "expr": "block_stat_after_txs_postponed{job=\"hived\"}",
     "legendFormat": "Postponed"
    }
   ]
  },
  {
   "title": "Block Execution Times",
   "type": "timeseries",
   "description": "Breakdown of block execution times",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "block_stat_exec_wait_time{job=\"hived\"}",
     "legendFormat": "Waiting Time"
    },
    {
     "expr": "block_stat_exec_cleanup_time{job=\"hived\"}",
     "legendFormat": "Cleanup Time"
    },
    {
     "expr": "block_stat_exec_work_time{job=\"hived\"}",
     "legendFormat": "Working Time"
    }
   ]
  },
  {
   "title": "Block Execution Total Time",
   "type": "timeseries",
   "description": "Total block execution time",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "block_stat_exec_total_time{job=\"hived\"}",
     "legendFormat": "Total Time"
    },
    {
     "expr": "avg_over_time(block_stat_exec_total_time{job=\"hived\"}[5m])",
     "legendFormat": "Total Time (5 minute MA)"
    }
   ]
  },
  { "title": "Dynamic Global Properties", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "HIVE Circulating Supply",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dgp_current_supply{job=\"hived_api\"}/1000",
     "legendFormat": "Circulating Supply"
    }
   ]
  },
  {
   "title": "HBD Circulating Supply",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dgp_current_hbd_supply{job=\"hived_api\"} / 1000",
     "legendFormat": "Circulating Supply"
    }
   ]
  },
  {
   "title": "HBD Circulating Supply (Excluding DHF)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(dgp_current_hbd_supply{job=\"hived_api\"} / 1000) - ignoring(name) account_hbd_balance{name=\"hive.fund\"}",
     "legendFormat": "Circulating Supply"
    }
   ]
  },
  {
   "title": "HIVE per MVests",
   "type": "stat",
   "description": "HIVE per 1 million vesting shares",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1000000000*dgp_total_vesting_fund_hive{job=\"hived_api\"}/(dgp_total_vesting_shares{job=\"hived_api\"})",
     "legendFormat": "Circulating Supply"
    }
   ]
  },
  {
   "title": "Percent HIVE Staked",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*dgp_total_vesting_fund_hive{job=\"hived_api\"}/(dgp_current_supply{job=\"hived_api\"}-ignoring(name) account_balance{name=\"hive.fund\"}*1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HIVE Circulating Supply",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "dgp_current_supply{job=\"hived_api\"}/1000",
     "legendFormat": "Circulating Supply (HIVE)"
    }
   ]
  },
  {
   "title": "HIVE Virtual Supply",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "dgp_virtual_supply{job=\"hived_api\"} / 1000",
     "legendFormat": "Virtual Supply (HIVE)"
    }
   ]
  },
  {
   "title": "HBD Circulating Supply",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "dgp_current_hbd_supply{job=\"hived_api\"} / 1000",
     "legendFormat": "Circulating Supply (HBD)"
    }
   ]
  },
  {
   "title": "HBD Circulating Supply (Excluding DHF)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "(dgp_current_hbd_supply{job=\"hived_api\"} / 1000) - ignoring(name) account_hbd_balance{name=\"hive.fund\"}",
     "legendFormat": "Circulating Supply (HBD)"
    }
   ]
  },
  {
   "title": "Percent HIVE Staked",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100*dgp_total_vesting_fund_hive{job=\"hived_api\"}/(dgp_current_supply{job=\"hived_api\"}-ignoring(name) account_balance{name=\"hive.fund\"}*1000)",
     "legendFormat": "Percent Staked"
    }
   ]
  },
  {
   "title": "HBD Balance In DHF",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "account_hbd_balance{name=\"hive.fund\"}",
     "legendFormat": "Balance (HBD)"
    }
   ]
  },
  {
   "title": "Accounts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "collapsed": true,
   "panels": [
    {
     "title": "Upvote Mana",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "account_mana{type=\"upvote\"} / 100",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Downvote Mana",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "account_mana{type=\"downvote\"} / 100",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "RC Mana",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "account_mana{type=\"rc\"} / 100",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Liquid HIVE Balance",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "HIVE" } },
     "targets": [
      {
       "expr": "account_balance{job=\"hived_api\", name!=\"hive.fund\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Liquid HBD Balance",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "HBD" } },
     "targets": [
      {
       "expr": "account_hbd_balance{job=\"hived_api\", name!=\"hive.fund\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Savings HIVE Balance",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "HIVE" } },
     "targets": [
      {
       "expr": "account_savings_balance{job=\"hived_api\", name!=\"hive.fund\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Savings HBD Balance",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "HBD" } },
     "targets": [
      {
       "expr": "account_savings_hbd_balance{job=\"hived_api\", name!=\"hive.fund\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Staked HIVE",
     "type": "timeseries",
     "description": "Staked HIVE owned by account",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "account_vesting_shares{job=\"hived_api\", type=\"staked_hive\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Staked HIVE (Mana)",
     "type": "timeseries",
     "description": "Staked HIVE after taking delegations and ongoing power downs into account usable for voting and RC mana",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "account_vesting_shares{job=\"hived_api\", type=\"current_hive\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}