scrape_configs:
  - job_name: 'hived'
    scrape_interval: 3s
    static_configs:
      - targets: ['http://localhost:8088']
  - job_name: 'hived_api'
    scrape_interval: 30s
    static_configs:
      - targets: ['http://localhost:8087']
